### ISSUE TITLE
Additional Information heading should not show if no additional info is configured [BUG]

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/Summit-Events-App#402] opened 2022-05-13 15:52 UTC
**Describe the bug**
There are no additional options configured on my event but the Additional Information heading is still displaying.

**To Reproduce**
1. Setup and event with a couple of standard questions
2. Make sure no additional information (e.g. questions) are setup.  Note that I did have them setup and removed them so the issue may be there if you try to reproduce with a fresh event and cannot reproduce.
3. Save the event, create an event instance, view the registration page.

**Expected behavior**
When no additional options configured on an event  the Additional Information heading should not display.

**Screenshots**
![image](https://user-images.githubusercontent.com/4521914/168320237-3d8aa7ae-2164-429e-a2d1-56a94bd61c87.png)

![image](https://user-images.githubusercontent.com/4521914/168320582-72713e0b-95a3-45c5-9082-548b0c6c61c6.png)

![image](https://user-images.githubusercontent.com/4521914/168321172-8f032567-0c60-4369-8aef-4735d8dcbc68.png)

**Comment by rdblake21** [comment] 2023-01-20 20:12
Unable to reproduce and believed that this was resolved earlier.  Closing due to inability to reproduce on current branch.

**Comment by rdblake21** [comment] 2023-01-20 20:24
Was able to recareate

**Comment by rdblake21** [comment] 2023-01-20 20:26
Was able to recreate and found on line 157 on the SummiEventRegisterController:

` if (
                    !String.isBlank(eventPage.Add_Info_Question_Type_1__c) ||
                            !String.isBlank(eventPage.Add_Info_Question_Type_1__c) ||
                            !String.isBlank(eventPage.Add_Info_Question_Type_1__c) ||
                            !String.isBlank(eventPage.Add_Info_Question_Type_1__c) ||
                            !String.isBlank(eventPage.Add_Info_Question_Type_1__c) ||
                            eventPage.Include_Time_frame_List__c ||
                            eventPage.Allow_Other_Attendees__c ||
                            (eventPage.Ask_Gender__c != 'Do not ask' && eventPage.Ask_Gender__c != null) ||
                            (eventPage.Ask_Registrant_Program_Of_Interest__c != 'Do not ask' && eventPage.Ask_Registrant_Program_Of_Interest__c != null)
                    ) {
                additionalQuestions = true;`


It should read:

`            if (
                    !String.isBlank(eventPage.Add_Info_Question_Type_1__c) ||
                            !String.isBlank(eventPage.Add_Info_Question_Type_2__c) ||
                            !String.isBlank(eventPage.Add_Info_Question_Type_3__c) ||
                            !String.isBlank(eventPage.Add_Info_Question_Type_4__c) ||
                            !String.isBlank(eventPage.Add_Info_Question_Type_5__c) ||
                            eventPage.Include_Time_frame_List__c ||
                            eventPage.Allow_Other_Attendees__c ||
                            (eventPage.Ask_Gender__c != 'Do not ask' && eventPage.Ask_Gender__c != null) ||
                            (eventPage.Ask_Registrant_Program_Of_Interest__c != 'Do not ask' && eventPage.Ask_Registrant_Program_Of_Interest__c != null)
                    ) {
                additionalQuestions = true;`

**Comment by rdblake21** [comment] 2023-01-20 20:29
This is happening particularly when the Question Type has a value, but the Question Text is blank.  When the Question Type has a value, but the text is blank, the question doesn't appear at all.

@tcdahlberg may want to consider updating the login here to reflect the Add_Info_Question_Text.  Otherwise it'll continue, but now with the other questions should there be a value and no Question Text.

**Closed as completed** 2023-01-26 21:09 UTC
Labels: bug, fix before release

**Comment by tcdahlberg** [comment] 2023-02-16 00:19
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment] 2023-02-17 18:09
Included in production release 0.28.0.2
